### ISSUE TITLE
CSS prop-like inspector

### ISSUE THREAD

**Issue by crcn** [crcn/tandem-old#696]
<img width="447" alt="Screenshot 2019-04-17 10 13 01" src="https://user-images.githubusercontent.com/757408/56290401-6fc7d080-60f9-11e9-9c94-96784b10ef51.png">

#### TODOS

- [ ] ⚠️ Validation
  - [ ] Variants
    - [ ] How to toggle them on instances
    - [ ] How to add a variant nested element
      - [ ] should be list of variants defined at component level
    - [ ] need to be able to toggle them at instance level
      - [ ] probably separate variants from styles and call them states instead
  - [ ] Mixins
    - [ ] not overridable since props are computed. Disable + button.
    - [ ] cannot add new properties
    - [ ] are computed properties
  - [ ] overriding
    - [ ] overriding variant styles? (needs to happen at style block level)
    - [ ] can add style block
    - [ ] flagging properties that are overridden
    - [ ] if mixins live in style panel
   - [ ] inherited style blocks
     - [ ] must be prioritized after element-specific style blocks (inherited show up at end)
     - [ ] cannot be re-organized. Must always be displayed at bottom.
     - [ ] editable properties?
   - [ ] instances
     - [ ] compute properties? Need to look into how this works with variants & inherited styles
     - [ ] cannot override style properties directly. Need to add style blocks instead (for consistency)
- [ ] CSS parser
- [ ] Style blocks need to be re-orderable
  - [ ] except for instance style blocks & inherited styles
- [ ] color picker for CSS functions
  - [ ] rgba
  - [ ] linear-gradient
  - [ ] hex
  - [ ] rgb
  - [ ] hsla
  - [ ] hsl
- [ ] dropdown option for certain properties
  - [ ] display
- [ ] ability to convert colors to different types (rgba -> hsla)
- [ ] dropdown support for enums (display, overflow)
- [ ] tooltip for entering enum
- [ ] tooltip for entering CSS prop
- [ ] support for variables
- [ ] `var` support (typing CSS function should display dropdown)
- [ ] CSS quick menu
  - [ ] each style prop should link to MDN docs
  - [ ] if no prop found, then display "press `enter` to add anyways"
- [ ] mixins
  - [ ] still live as separate type 
     - [ ] needed since mixins should be able to combine other mixins
  - [ ] can define any style block as a mixin (doing so moves mixin to global place)
- [ ] style block settings
  - [ ] convert to "mixin" option
  - [ ] if mixin, then "convert to style block" option
  - [ ] "change type" option
- [ ] variant behavior

**Comment by crcn** [comment]
MVP UI:

<img width="365" alt="Screenshot 2019-04-17 22 05 43" src="https://user-images.githubusercontent.com/757408/56330100-ff529b00-615c-11e9-8a23-3ee64a8ead9c.png">

Wired up:

![responsive-design](https://user-images.githubusercontent.com/757408/56330110-08dc0300-615d-11e9-92c9-8ee04a2a7e3e.gif)

**Comment by crcn** [comment]
Update:

<img width="434" alt="Screenshot 2019-08-14 18 55 33" src="https://user-images.githubusercontent.com/757408/63062015-4b240f80-bec5-11e9-9309-17c32842cc4a.png">
