### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by crcn** [crcn/tandem-old#724]
#### TODOS:
- [ ] VSCode preview
- [ ] ability to update vfs content
- [ ] JS renderer
- [ ] diffing & patching
- [ ] React compiler
- [ ] static HTML compiler
- [ ] Documentation
- [ ] DSL
  - [x] import statements should work
  - [ ] render context data (should handle strings, numbers)
  - [ ] scoped styles
  - [ ] basic slots
  - [ ] conditional statements
  - [ ] explicit properties
  - [ ] importing JSON context 
  - [ ] attribute spread operator
  - [ ] ability to omit
  - [ ] linting
    - [ ] warning when native properties (class) applied to component that renders fragment
    - [ ] warning when CSS selectors are targeting element
    - [ ] warning when properties are not used
    - [ ] lint config
      - [ ] ability to require explicit properties
    - [ ] infer properties
    - [ ] error when property is missing
   
- [ ] bug fixes
  - [ ] dependency graph should use absolute paths
  - [ ] repeated lists
  - [ ] attribute binding
