### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by crcn** [crcn/tandem-old#744]
#### Todos

- [ ] rust linter setup
- [ ] prevent slots for `id` attributes
- [ ] prevent slot attributes for part, preview, import
