### ISSUE TITLE
Inferencing

### ISSUE THREAD

**Issue by crcn** [crcn/tandem-old#745]
Depends on #744

#### Todos

- [ ] Replace TS inferencer
- [ ] Hook into Linter
- [ ] Error when prop is missing

#### Considerations

- Error messages may get annoying for props reserved to code (such as listeners)
