### ISSUE TITLE
Initial Docs

### ISSUE THREAD

**Issue by crcn** [crcn/tandem-old#748]
### Todos

- [ ] README.md
  - [ ] What it is
  - [ ] brief example
  - [ ] feature
  - [ ] getting started
  - [ ] Syntax 
    - [ ] `<part />`
    - [ ] `<self />`
    - [ ] `<preview />`
    - [ ] `{slots}`
     - [ ] attributes
     - [ ] text
     - [ ] JSON
   - [ ] Integrations
     - [ ] React
       - [ ] how to import parts
       - [ ] organizing code
       - [ ] `styled` utils
       - [ ] typed generation files
       - [ ] webpack config
- [ ] VSCE docs
  - [ ] commands
  - [ ] What to do if you don't have VSCode
- [ ] examples
  - [x] React TODO MVC
  - [x] simple todo
